language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.5"
  - "2.2.0"
script: bundle exec rake spec
before_install:
  - sudo add-apt-repository -y ppa:shiki/mediainfo
  - sudo apt-get update -qq
  - sudo apt-get install -y libmediainfo-dev mediainfo